"""Файл с константами"""
msg_start_menu = "Меню"
btn_start_menu_ct = "Расписание"
btn_start_menu_ntf = "Уведомления"

msg_ct = "Уточните какое расписание вам вывести"
btn_ct_full = "Полное"

btn_week_ = "Неделя"
btn_week_current = "Эта неделя"
btn_week_next = "След. неделя"
btn_weekday = "День недели"

msg_day_btns = "Уточните день недели"
btn_day_ = "День"
btn_day_today = "Сегодня"
btn_day_tomorrow = "Завтра"
btn_day_mon = "Понедельник"
btn_day_tue = "Вторник"
btn_day_wed = "Среда"
btn_day_thu = "Четверг"
btn_day_fri = "Пятница"
btn_day_sat = "Суббота"
btn_day_sun = "Воскресенье"

file_path_class_timetable = "data/ClassTimetable.csv"

msg_ct_delimiter = "-------------------"
msg_ct_weekday = "День недели:"
msg_ct_lesson_start = "Начало:"
msg_ct_lesson_end = "Конец:"
msg_ct_lesson_name = "Предмет:"
msg_ct_teacher_name = "Преподаватель:"
msg_ct_is_every_w = "Еженедельно"
msg_ct_is_even_w = "Неделя: четная"
msg_ct_is_odd_w = "Неделя: нечетная"
msg_ct_is_once_month = "Раз в месяц"
msg_ct_is_online = "Онлайн"
msg_ct_is_offline = "Офлайн"
msg_ct_other_info = "Другая информация:"

msg_ct_not = "занятий нет"
msg_true = "Да"
msg_false = "Нет"

msg_ntf = "Настройте уведомления"
btn_ntf_bef_lsn = "Перед началом занятия"
btn_ntf_every_day = "В день занятия"
btn_ntf_bef_lesson_h2 = "За 2 часа"
btn_ntf_bef_lesson_h1 = "За час"
btn_ntf_bef_lesson_min30 = "За 30 минут"
btn_ntf_bef_lesson_min15 = "За 15 минут"
btn_ntf_les = "За 2 часа"
